# coding: utf-8

"""
    Root.io API

    This is the API documentation for Root.io.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from root_io.sdk.cloud_client.api.security_findings_api import SecurityFindingsApi


class TestSecurityFindingsApi(unittest.TestCase):
    """SecurityFindingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SecurityFindingsApi()

    def tearDown(self) -> None:
        pass

    def test_orgs_org_id_security_findings_finding_id_comments_comment_id_delete(self) -> None:
        """Test case for orgs_org_id_security_findings_finding_id_comments_comment_id_delete

        Delete a comment from a security finding
        """
        pass

    def test_orgs_org_id_security_findings_finding_id_comments_comment_id_put(self) -> None:
        """Test case for orgs_org_id_security_findings_finding_id_comments_comment_id_put

        Update a comment to a security finding
        """
        pass

    def test_orgs_org_id_security_findings_finding_id_comments_post(self) -> None:
        """Test case for orgs_org_id_security_findings_finding_id_comments_post

        Adds a comment to a security finding
        """
        pass

    def test_orgs_org_id_security_findings_finding_id_status_put(self) -> None:
        """Test case for orgs_org_id_security_findings_finding_id_status_put

        Updates security finding status and resolution
        """
        pass

    def test_orgs_org_id_security_findings_get(self) -> None:
        """Test case for orgs_org_id_security_findings_get

        List security findings
        """
        pass

    def test_orgs_org_id_security_findings_report_get(self) -> None:
        """Test case for orgs_org_id_security_findings_report_get

        Export a security findings file
        """
        pass


if __name__ == '__main__':
    unittest.main()
