# coding: utf-8

"""
    Root.io API

    This is the API documentation for Root.io.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from root_io.sdk.cloud_client.api.v_scan_reports_api import VScanReportsApi


class TestVScanReportsApi(unittest.TestCase):
    """VScanReportsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VScanReportsApi()

    def tearDown(self) -> None:
        pass

    def test_orgs_org_id_vscan_reports_upload_post(self) -> None:
        """Test case for orgs_org_id_vscan_reports_upload_post

        Upload VScan Report
        """
        pass


if __name__ == '__main__':
    unittest.main()
