# coding: utf-8

"""
    Root.io API

    This is the API documentation for Root.io.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from root_io.sdk.cloud_client.api.invite_api import InviteApi


class TestInviteApi(unittest.TestCase):
    """InviteApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InviteApi()

    def tearDown(self) -> None:
        pass

    def test_orgs_org_id_invites_invite_id_acceptance_post(self) -> None:
        """Test case for orgs_org_id_invites_invite_id_acceptance_post

        Accepts an organization invite
        """
        pass

    def test_orgs_org_id_invites_post(self) -> None:
        """Test case for orgs_org_id_invites_post

        Creates an organization invite
        """
        pass


if __name__ == '__main__':
    unittest.main()
