# coding: utf-8

"""
    Root.io API

    This is the API documentation for Root.io.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from root_io.sdk.cloud_client.models.api_key import APIKey

class TestAPIKey(unittest.TestCase):
    """APIKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIKey:
        """Test APIKey
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIKey`
        """
        model = APIKey()
        if include_optional:
            return APIKey(
                account_id = '',
                active = True,
                created_at = '',
                expires_at = '',
                id = '',
                key = '',
                name = '',
                updated_at = ''
            )
        else:
            return APIKey(
        )
        """

    def testAPIKey(self):
        """Test APIKey"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
