# coding: utf-8

"""
    Root.io API

    This is the API documentation for Root.io.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from root_io.sdk.cloud_client.api.api_keys_api import APIKeysApi


class TestAPIKeysApi(unittest.TestCase):
    """APIKeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = APIKeysApi()

    def tearDown(self) -> None:
        pass

    def test_api_keys_get(self) -> None:
        """Test case for api_keys_get

        List API Keys
        """
        pass

    def test_api_keys_id_delete(self) -> None:
        """Test case for api_keys_id_delete

        Delete API Key
        """
        pass

    def test_api_keys_id_get(self) -> None:
        """Test case for api_keys_id_get

        Show API Key
        """
        pass

    def test_api_keys_post(self) -> None:
        """Test case for api_keys_post

        Create API Key
        """
        pass


if __name__ == '__main__':
    unittest.main()
