# coding: utf-8

"""
    Root.io API

    This is the API documentation for Root.io.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from root_io.sdk.cloud_client.models.create_org_invite_request import CreateOrgInviteRequest

class TestCreateOrgInviteRequest(unittest.TestCase):
    """CreateOrgInviteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrgInviteRequest:
        """Test CreateOrgInviteRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrgInviteRequest`
        """
        model = CreateOrgInviteRequest()
        if include_optional:
            return CreateOrgInviteRequest(
                role = 'member'
            )
        else:
            return CreateOrgInviteRequest(
                role = 'member',
        )
        """

    def testCreateOrgInviteRequest(self):
        """Test CreateOrgInviteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
