# coding: utf-8

"""
    Root.io API

    This is the API documentation for Root.io.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from root_io.sdk.cloud_client.models.entities_scanner_name import EntitiesScannerName

class TestEntitiesScannerName(unittest.TestCase):
    """EntitiesScannerName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntitiesScannerName(self):
        """Test EntitiesScannerName"""
        # inst = EntitiesScannerName()

if __name__ == '__main__':
    unittest.main()
