# coding: utf-8

"""
    Root.io API

    This is the API documentation for Root.io.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from root_io.sdk.cloud_client.models.entities_finding_status import EntitiesFindingStatus

class TestEntitiesFindingStatus(unittest.TestCase):
    """EntitiesFindingStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntitiesFindingStatus(self):
        """Test EntitiesFindingStatus"""
        # inst = EntitiesFindingStatus()

if __name__ == '__main__':
    unittest.main()
