# coding: utf-8

"""
    Root.io API

    This is the API documentation for Root.io.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from root_io.sdk.cloud_client.models.account import Account

class TestAccount(unittest.TestCase):
    """Account unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Account:
        """Test Account
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Account`
        """
        model = Account()
        if include_optional:
            return Account(
                created_at = '',
                email = '',
                external_id = '',
                id = '',
                last_login_at = '',
                name = '',
                org_role_bindings = [
                    root_io.sdk.cloud_client.models.org_role_binding.OrgRoleBinding(
                        account_id = '', 
                        created_at = '', 
                        id = '', 
                        organization = root_io.sdk.cloud_client.models.organization.Organization(
                            created_at = '', 
                            id = '', 
                            name = '', 
                            updated_at = '', ), 
                        organization_id = '', 
                        role = '', 
                        updated_at = '', )
                    ],
                provider = '',
                updated_at = ''
            )
        else:
            return Account(
                email = '',
                external_id = '',
                name = '',
        )
        """

    def testAccount(self):
        """Test Account"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
