# coding: utf-8

"""
    Root.io API

    This is the API documentation for Root.io.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from root_io.sdk.cloud_client.models.entities_scanner_name import EntitiesScannerName
from root_io.sdk.cloud_client.models.entities_vscan_report_upload_status import EntitiesVscanReportUploadStatus
from typing import Optional, Set
from typing_extensions import Self

class VscanReportUpload(BaseModel):
    """
    VscanReportUpload
    """ # noqa: E501
    created_at: Optional[StrictStr] = None
    external_scan_ids: Optional[StrictStr] = None
    file_url: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    organization_id: Optional[StrictStr] = None
    scanner_name: Optional[EntitiesScannerName] = None
    status: Optional[EntitiesVscanReportUploadStatus] = None
    updated_at: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["created_at", "external_scan_ids", "file_url", "id", "organization_id", "scanner_name", "status", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VscanReportUpload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VscanReportUpload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "external_scan_ids": obj.get("external_scan_ids"),
            "file_url": obj.get("file_url"),
            "id": obj.get("id"),
            "organization_id": obj.get("organization_id"),
            "scanner_name": obj.get("scanner_name"),
            "status": obj.get("status"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


